In [1]:
height = [10,20,40,55,76]
weight = [50,45,65,78,95]
height/weight

TypeError: unsupported operand type(s) for /: 'list' and 'list'

As shown above example we wanted to divide height/weight one by one respective values according to same indexes but list is not supported to '/' operand

Using numpy we get the results

In [4]:
#  !pip install numpy # to install the package numpy 
import numpy as np

# NumPy Array creation

In [5]:
height = [10,20,40,55,76]
weight = [50,45,65,78,95]
np_height = np.array(height)
np_weight = np.array(weight)
print(np_height)
print(np_weight)

[10 20 40 55 76]
[50 45 65 78 95]


In [6]:
print(type(np_height),type(np_weight))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


the arrays look like lists but they are not 

In [7]:
div = np_weight/np_height
div

array([5.        , 2.25      , 1.625     , 1.41818182, 1.25      ])

Element wise calculation is done here

### Numpy Subsetting 

In [8]:
np_weight>60

array([False, False,  True,  True,  True])

In [9]:
np_weight[np_weight>60]

array([65, 78, 95])

In [10]:
#  1D Array
l = [1,2,3,4,4]
ar = np.array(l)
print(ar)
print(ar.shape)
print(ar.ndim)
print(np.size(ar))
print(len(ar))

[1 2 3 4 4]
(5,)
1
5
5


In [11]:
# 2D Array
ar = np.array([[1,2,3],[1,4,4],[1,45,5],[4,5,6]])
print(ar)
print(ar.shape)
print(ar.ndim)
print(np.size(ar))
print(len(ar))

[[ 1  2  3]
 [ 1  4  4]
 [ 1 45  5]
 [ 4  5  6]]
(4, 3)
2
12
4


In [12]:
# use of arrange()
ar = np.arange(1,10)
print(ar)
print(ar.shape)
print(ar.ndim)
print(np.size(ar))
print(len(ar))

[1 2 3 4 5 6 7 8 9]
(9,)
1
9
9


##### use of linspace

In [13]:
# numbers between 1 to 10 ,length is 450
ar = np.arange(1,10,(9/450))

In [14]:
ar2 = np.linspace(1,10,450)# above code can be written using linspace(start,stop,number)
len(ar2) 

450

#### use of random

In [15]:
np.random.rand(1,4) # random numbers 0 to 1

array([[0.21147572, 0.14682014, 0.13153829, 0.20490976]])

In [16]:
np.random.randn(1,4) # n for  normal distribution

array([[-1.32553946,  0.42035364, -2.15421761,  1.11812034]])

In [17]:
np.random.randint(1,9 ,size=(4,4))

array([[8, 2, 6, 1],
       [3, 3, 6, 7],
       [2, 1, 8, 4],
       [5, 4, 4, 7]])

# series of ones and zeroes

In [18]:
z = np.zeros([1,10])
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
print(type(z))
z.dtype

<class 'numpy.ndarray'>


dtype('float64')

In [20]:
o = np.ones([1,10],dtype='int')
o

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
np.diag(i)

array([1., 1., 1.])

## Indexing /slicing /accessing NumPy Arrays

In [24]:
ar = np.random.randint(1,10,size=6)
ar

array([3, 5, 1, 7, 6, 8])

In [25]:
ar[1]

5

In [26]:
ar[-1]

8

In [27]:
ar[len(ar)-1]

8

In [28]:
ar[:3]

array([3, 5, 1])

In [29]:
ar[1:5]

array([5, 1, 7, 6])

In [30]:
mat = np.random.rand(4,4)
mat

array([[5.09170867e-01, 9.65197572e-01, 9.80356902e-01, 2.67622597e-01],
       [8.25007311e-01, 1.85554687e-01, 3.63703191e-01, 4.08439206e-01],
       [4.33034829e-01, 8.12897856e-01, 1.50190683e-01, 6.71338821e-01],
       [9.92684487e-01, 5.30544590e-01, 4.05270745e-04, 4.86899745e-01]])

In [31]:
mat = np.round(mat,2)
mat

array([[0.51, 0.97, 0.98, 0.27],
       [0.83, 0.19, 0.36, 0.41],
       [0.43, 0.81, 0.15, 0.67],
       [0.99, 0.53, 0.  , 0.49]])

In [32]:
mat = np.round(np.random.rand(4,4),2)
mat

array([[0.11, 0.7 , 0.91, 0.29],
       [0.54, 0.83, 0.79, 0.72],
       [0.51, 0.96, 0.73, 0.07],
       [0.75, 0.71, 0.83, 0.06]])

### Subsetting

In [33]:
mat[2,3]

0.07

In [34]:
mat[:,3]  #mat[0:4,3]

array([0.29, 0.72, 0.07, 0.06])

In [35]:
mat[1:3,1:3]# acessing middle elements


array([[0.83, 0.79],
       [0.96, 0.73]])

In [36]:
mat[1:3,0:2]# acessing (1st row and 2nd rows ) and( 0th column and 1st column)

array([[0.54, 0.83],
       [0.51, 0.96]])

In [37]:
mat[0,:]

array([0.11, 0.7 , 0.91, 0.29])

- acssessing elemts by discrete way
- getting corner values

In [38]:
m1 = mat[[0,3],:]# acessing 0th row and last row
print(m1)
m1[:,[0,3]]# acessing corner elements of original matrix

[[0.11 0.7  0.91 0.29]
 [0.75 0.71 0.83 0.06]]


array([[0.11, 0.29],
       [0.75, 0.06]])

In [39]:
m1[:,[0,3]]

array([[0.11, 0.29],
       [0.75, 0.06]])

In [40]:
mat


array([[0.11, 0.7 , 0.91, 0.29],
       [0.54, 0.83, 0.79, 0.72],
       [0.51, 0.96, 0.73, 0.07],
       [0.75, 0.71, 0.83, 0.06]])

### Reshape

In [41]:
# reshape concept

print(mat.reshape([1,16]))
print(mat.reshape([1,-1])) #if u dont know the size but u want in single row
print(mat.reshape([-1,1])) #if u dont know the size but u want in single column

[[0.11 0.7  0.91 0.29 0.54 0.83 0.79 0.72 0.51 0.96 0.73 0.07 0.75 0.71
  0.83 0.06]]
[[0.11 0.7  0.91 0.29 0.54 0.83 0.79 0.72 0.51 0.96 0.73 0.07 0.75 0.71
  0.83 0.06]]
[[0.11]
 [0.7 ]
 [0.91]
 [0.29]
 [0.54]
 [0.83]
 [0.79]
 [0.72]
 [0.51]
 [0.96]
 [0.73]
 [0.07]
 [0.75]
 [0.71]
 [0.83]
 [0.06]]


In [42]:
mat.reshape([2,8])

array([[0.11, 0.7 , 0.91, 0.29, 0.54, 0.83, 0.79, 0.72],
       [0.51, 0.96, 0.73, 0.07, 0.75, 0.71, 0.83, 0.06]])

# Numpy Operation


In [43]:
a1 = np.random.randint(5,size=(1,10))
a2 = np.random.randint(5,size=(1,10))
print(a1)
print(a2)

[[0 0 1 1 0 3 2 1 1 0]]
[[3 0 3 0 2 0 1 0 1 3]]


In [44]:
# element wise addition
print(a1+a2)
np.add(a1,a2)

[[3 0 4 1 2 3 3 1 2 3]]


array([[3, 0, 4, 1, 2, 3, 3, 1, 2, 3]])

In [45]:
# element wise substraction
np.subtract(a1,a2)

array([[-3,  0, -2,  1, -2,  3,  1,  1,  0, -3]])

In [46]:
np.multiply(a1,a2)

array([[0, 0, 3, 0, 0, 0, 2, 0, 1, 0]])

In [47]:
np.divide(a1,a2)

C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.        ,        nan, 0.33333333,        inf, 0.        ,
               inf, 2.        ,        inf, 1.        , 0.        ]])

In [48]:
np.mod(a1,a2)

C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in remainder
  """Entry point for launching an IPython kernel.


array([[0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [49]:
a1 = np.random.randint(5,size=(3,3))
a2 = np.random.randint(5,size=(3,3))
print(a1)
print(a2)

[[0 4 0]
 [0 0 3]
 [2 1 1]]
[[3 4 2]
 [1 0 4]
 [2 2 0]]


In [50]:
mul = np.multiply(a1,a2)
mul

array([[ 0, 16,  0],
       [ 0,  0, 12],
       [ 4,  2,  0]])

In [51]:
np.dot(a1,a2)

array([[ 4,  0, 16],
       [ 6,  6,  0],
       [ 9, 10,  8]])

In [52]:
a1@a2

array([[ 4,  0, 16],
       [ 6,  6,  0],
       [ 9, 10,  8]])

In [53]:
a1 = np.random.randint(5,size=(1,10))
a2 = np.random.randint(5,size=(1,10))
print(a1)
print(a2)

[[1 2 2 0 2 4 0 4 1 1]]
[[1 1 0 2 1 3 4 0 4 3]]


In [54]:
a1 = np.squeeze(a1)
print(a1)
a2 = np.squeeze(a2)
print(a2)
np.dot(a1,a2)

[1 2 2 0 2 4 0 4 1 1]
[1 1 0 2 1 3 4 0 4 3]


24

In [55]:
m1 = np.random.randint(5,size=(4,4))
m2 = np.random.randint(5,size=(5,4))
print(m1)
print(m2)

[[3 1 0 1]
 [0 0 3 4]
 [3 1 0 1]
 [2 3 2 0]]
[[2 0 4 3]
 [3 1 2 3]
 [2 3 3 1]
 [0 0 0 1]
 [0 4 2 1]]


In [56]:
m22 = m2[:4,]
m22

array([[2, 0, 4, 3],
       [3, 1, 2, 3],
       [2, 3, 3, 1],
       [0, 0, 0, 1]])

In [57]:
m1*m22

array([[ 6,  0,  0,  3],
       [ 0,  0,  6, 12],
       [ 6,  3,  0,  1],
       [ 0,  0,  0,  0]])

In [58]:
np.dot(m1,m22)

array([[ 9,  1, 14, 13],
       [ 6,  9,  9,  7],
       [ 9,  1, 14, 13],
       [17,  9, 20, 17]])

In [59]:
m2.T

array([[2, 3, 2, 0, 0],
       [0, 1, 3, 0, 4],
       [4, 2, 3, 0, 2],
       [3, 3, 1, 1, 1]])

In [60]:
np.dot(m1,m2.T)

array([[ 9, 13, 10,  1,  5],
       [24, 18, 13,  4, 10],
       [ 9, 13, 10,  1,  5],
       [12, 13, 19,  0, 16]])

In [61]:
a1 = np.random.randint(5,size=(1,10))
np.log(a1)

C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([[      -inf, 1.38629436, 1.09861229, 1.38629436, 0.        ,
        1.38629436, 0.        , 0.        , 1.09861229,       -inf]])

In [62]:
np.log10(a1)

C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.60205999, 0.47712125, 0.60205999, 0.        ,
        0.60205999, 0.        , 0.        , 0.47712125,       -inf]])

In [63]:
np.log2(a1)

C:\Users\ab522tx\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log2
  """Entry point for launching an IPython kernel.


array([[     -inf, 2.       , 1.5849625, 2.       , 0.       , 2.       ,
        0.       , 0.       , 1.5849625,      -inf]])

In [64]:
np.exp(a1)

array([[ 1.        , 54.59815003, 20.08553692, 54.59815003,  2.71828183,
        54.59815003,  2.71828183,  2.71828183, 20.08553692,  1.        ]])

In [65]:
np.power(a1,2)

array([[ 0, 16,  9, 16,  1, 16,  1,  1,  9,  0]], dtype=int32)

In [66]:
np.std(a1)

1.57797338380595

In [67]:
np.mean(a1)

2.1

In [68]:
np.median(a1)

2.0

In [69]:
np.var(a1)

2.4899999999999998

In [70]:
np.concatenate([a1,a1])


array([[0, 4, 3, 4, 1, 4, 1, 1, 3, 0],
       [0, 4, 3, 4, 1, 4, 1, 1, 3, 0]])

In [71]:
m1 = np.random.randint(5,size=(2,4))
m2 = np.random.randint(5,size=(2,4))

In [72]:
print(m1)
print(m2)

[[0 2 4 4]
 [0 1 3 2]]
[[4 4 4 3]
 [4 0 1 1]]


In [73]:
np.hstack([m1,m2])

array([[0, 2, 4, 4, 4, 4, 4, 3],
       [0, 1, 3, 2, 4, 0, 1, 1]])

In [74]:
np.vstack([m1,m2])

array([[0, 2, 4, 4],
       [0, 1, 3, 2],
       [4, 4, 4, 3],
       [4, 0, 1, 1]])

In [75]:
data = np.random.randint(5,size=(1,4))
data

array([[1, 1, 0, 1]])

In [76]:
ind = np.where(data<5)

In [77]:
data[ind]

array([1, 1, 0, 1])

In [78]:
data[ind] = data[ind]+3

In [79]:
data

array([[4, 4, 3, 4]])